# Generated by Django 3.1.6 on 2021-06-11 17:37

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidModel',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(db_column='CITY', max_length=50)),
                ('date', models.DateField(db_column='DATE')),
                ('state', models.CharField(db_column='STATE', max_length=3)),
                ('estimated_population', models.IntegerField(db_column='ESTIMATED_POPULATION')),
                ('last_available_confirmed', models.IntegerField(db_column='LAST_AVAILABLE_CONFIRMED')),
                ('new_deaths', models.IntegerField(db_column='NEW_DEATHS')),
                ('new_confirmed', models.IntegerField(db_column='NEW_CONFIRMED')),
                ('last_available_deaths', models.IntegerField(db_column='LAST_AVAILABLE_DEATHS')),
                ('last_available_death_rate', models.FloatField(db_column='LAST_AVAILABLE_DEATH_RATE')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
